### ISSUE TITLE
Custom table name for `transactions`

### ISSUE THREAD

**Issue by elnurxf** [021-projects/laravel-wallet#1]
Try to update migration and modify `transactions` to `balance_transactions` also consider update config/wallet.php accordingly.

Since default model `\O21\LaravelWallet\Models\Transaction::class` using default table name assuming model name, this should be fixed to get table from config like: 

````
/**
 * The table associated with the model.
 *
 * @var string
 */
protected $table = config('wallet.table_names.transactions');

**Comment by 021-projects** [comment]
Hey there! Thanks for reporting! Fixed in https://github.com/021-projects/laravel-wallet/commit/70db834ec8f723a2aa517954058cc9a729a92e69
