### ISSUE TITLE
Function to Edit Transactions

### ISSUE THREAD

**Issue by notwhoyouexpected** [021-projects/laravel-wallet#10]
Wouldn't a function to edit transactions be useful?something like $transaction->change($amount,$commision = null) which automatically changes the amount,commission, received amount and generates user balances all in one.

**Comment by notwhoyouexpected** [comment]
also maybe open the discussion tab in github so people can use this for feature requests, questiosn etc.

**Comment by 021-projects** [comment]
Hey! 
You can simply update the model fields and all associated values ​​will be updated automatically :)

Good idea for discussions! Thank you!
