### ISSUE TITLE
How do I do Transaction Updated At

### ISSUE THREAD

**Issue by user3470** [021-projects/laravel-wallet#11]
When I update transaction status from Pending to Success I would like to know the time when it was updated. How do I achieve that?

**Comment by 021-projects** [comment]
Hey! 

1. Create a migration where you add the `updated_at` field for `transactions` table:
`$table->timestamp('updated_at')->nullable();`
2. Create own transaction model and extend it with `\O21\LaravelWallet\Models\Transaction` class
3. [Override default transaction model](https://021-projects.github.io/laravel-wallet/9.x/configuration.html#overriding-default-models)
4. Determinate `UPDATED_AT` constant in your model:
`const UPDATED_AT = 'updated_at';`
