### ISSUE TITLE
Allow installation with Laravel 11

### ISSUE THREAD

**Issue by A-Raileanu** [021-projects/laravel-wallet#2]
I've successfully tested the package with Laravel 11 and it operates as expected. Could you enable its installation for this version?

**Comment by 021-projects** [comment]
Hey! Installed Laravel 11, tried to run tests and everything was red. It seems that in Laravel 11 there have been high impact changes in migrations and working with database transactions. I'll figure this out closer to release :)

**Comment by 021-projects** [comment]
https://github.com/021-projects/laravel-wallet/commit/aa6d1db0a6837407d9df5fcf33161d360e7b162a
