### ISSUE TITLE
Add Option in Settings for UUID Support

### ISSUE THREAD

**Issue by notjustanothergithubuser** [021-projects/laravel-wallet#5]
Hi, cool package but sadly i cant use it without support for uuids, could you implment a option for that`?

**Comment by notjustanothergithubuser** [comment]
Can be done by chaning morphs with UuidMorphs in migrations :)

**Comment by 021-projects** [comment]
Hello! Did you mean uuid for transactions? This option is implemented in 9.x (dev)
https://github.com/021-projects/laravel-wallet/commit/c0933c19dab522b791ca10f03014a0a42de53a46

**Comment by notjustanothergithubuser** [comment]
no, if you have uuids as user id it wont work, so i though it would be maybe a good idea to include that in the options that oyu can change between uuids and ids ... but after thinking about it to write it in the docs would make more sense :) 


Also i have another questions, is it possible to set a status of a transaction to "ON_HOLD" while its on hold it already out of the senders balance but still not in the recivers balance as it needs first success? i tried to do that but didnt worked like i needed..
