### ISSUE TITLE
Collision with Laravel Cashier

### ISSUE THREAD

**Issue by notwhoyouexpected** [021-projects/laravel-wallet#6]
Hi, when you have Laravel Cashier installed you get "Trait method O21\LaravelWallet\Models\Concerns\HasBalance::balance has not been applied as App\Models\User::balance, because of collision with Laravel\Cashier\Billable::balance"

**Comment by 021-projects** [comment]
Hi! It seems this can be solved by replacing the function name when importing `Billable` trait:

```php
use Laravel\Cashier\Billable;
use O21\LaravelWallet\Models\Concerns\HasBalance;
use O21\LaravelWallet\Contracts\Payable; 
 
class User extends Authenticatable implements Payable
{
    use Billable {
        balance as cashierBalance;
    }
    use HasBalance;
}
```
