### ISSUE TITLE
`Feature` Allow balance to be charged for the max amount

### ISSUE THREAD

**Issue by GunniBusch** [021-projects/laravel-wallet#7]
It would be nice, if you could have a feature like Overcharge, but it won't overcharge, but return the balance, that is still due. And remove the possible amount.

This would allow the combination with other payment systems.

example
```
$remaining = charge(10,"USD")->from($user)->max()->commit();

// Somehow return missing funds, but not throwing error;

```

**Comment by 021-projects** [comment]
Hi! You can just charge all entire available balance:
```php
$balance = $user->balance('USD');
$tx = charge($balance->value, 'USD')->from($user)->commit();
$remaining = $balance->value;
```

**Comment by GunniBusch** [comment]
Thanks. But that's not going to work, because then the balance is 0.

 example: I have 30$ balance and want to buy something for 100$, then this works
if I have 2000, I could just submit the price.

But I am not sure, how to mitigate possible race conditions, between the calculation and a possible other change to the balance.

**Comment by 021-projects** [comment]
I don't quite understand what problem needs to be solved.  Could you please give an example of a real situation you encountered?
