### ISSUE TITLE
Get Balance History

### ISSUE THREAD

**Issue by notwhoyouexpected** [021-projects/laravel-wallet#8]
Hi, i want to create a Chart to display the balance history foreach month, is there any function how i can get the balance value from date XY? 

Thanks

**Comment by 021-projects** [comment]
Hey! Yes, for this you need to enable balance states log:
- [Log Balance States](https://021-projects.github.io/laravel-wallet/9.x/configuration.html#log-balance-states)

To get the records, access the `balanceStates()` method in the user model:
```php
$user->balanceStates()->where('created_at', '>', now()->subDays(30))->whereCurrency('USD')->get();
```

Tip: [Command to rebuild logs for existing transactions](https://021-projects.github.io/laravel-wallet/9.x/commands.html#rebuild-transaction-balance-states)
